export const DEFAULT_EXPRESSION_TYPE = 'RE'
export const DEFAULT_STATE_PREFIX_TASK_EXPRESSION = 'q'
export const DEFAULT_STATE_PREFIX_SOLUTION_EXPRESSION = 'z'
export const DEFAULT_OR_OPERATOR_EXPRESSION = '|'
